### ISSUE TITLE
add `disable-breakpoint` and `enable-breakpoint` functions

### ISSUE THREAD

**Issue by eoneill** [linkedin/archetype#99]
should be able to do...

``` scss
// disable the smartphone breakpoint
$a: disable-breakpoint(smartphone);
@include breakpoint(smartphone) {
  // nothing is output here...
}

$a: enable-breakpoint(smartphone);
@include breakpoint(smartphone) {
  // will output the correct media query
}
```
